dist: bionic
sudo: false

language: node_js
node_js:
  - '12'
  - '14'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run lint
  - npm run prettier:check
  - npm run build:lib
# We do not currently have any tests..
#  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

cache:
  directories:
    - ./node_modules
