dist: bionic
sudo: false

language: node_js
node_js:
  - "12"
  - "14"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run lint
  - npm run build:lib
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

cache:
  directories:
    - ./node_modules
